ci: add commit blacklist in run_tests.yml

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -29,6 +29,13 @@ jobs:
       - name: Checkout 🛎️
         uses: actions/checkout@v2.3.1
 
+      - name: Check commit blacklist
+        run: |
+          if grep -q '"rollup/wasm-node"' package.json; then
+            echo "Error: 'rollup/wasm-node' found in package.json"
+            exit 1
+          fi
+         
       - name: Build 🔧
         run: |
           make dist/cata/.dirstamp
